name: Check New Entry
on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:
permissions: write-all
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NOSTR_PRIVATE_KEY: ${{ secrets.NOSTR_PRIVATE_KEY }}
      BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: check
        run: |
          npm install ts-node
          npm install
          npm run check
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name beefriends
          git config user.email ${{ secrets.BEEFRIENDS_EMAIL_ADDRESS }}
          git add .
          git commit -m 'found new entry'
          git push
        if: steps.diff.outcome == 'failure'
